### PR TITLE
Added support for nga11y-form if there is multiple forms in the view.

### PR DESCRIPTION
**Pull request by chandramuralis**
nga11y-form directive will not work properly if we have more than one form in the view. It will set the focus on the last form on the view even though we submit first form. This commit should fix that issue.

### CODE REVIEW

**Comment by chandramuralis** [comment]
@dylanb  Could you please go through this pull request ?

**Comment by marcysutton** [comment]
Hi @chandramuralis, thanks for your contribution! How about adding a test for multiple forms? I can help, if needed.

**Comment by chandramuralis** [comment]
Sure I can create some unit tests if you can point me to which file I should add my cases.

**Comment by marcysutton** [comment]
@chandramuralis it looks like we would need to add `test/nga11yforms.js`, as it doesn't exist yet. I created a basic skeleton and pushed it to a branch to save you some time: https://github.com/dequelabs/ngA11y/blob/wip-forms-tests/test/nga11yforms.js

**Comment by marcysutton** [comment]
I've written a test for this and made some changes, @chandramuralis do you mind checking out #28?

**Comment by chandramuralis** [comment]
Seems like this is taken care as part of #28. Closing the pull request

**Comment by chandramuralis** [comment]
This change is not being released, is there any plan to release this change?

**Pull request closed without merging**
